name: Workflow Dispatch Unit Tests

on:
  # Runs when pushing commits & allows to manually run through Actions tab
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3.4.1
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Clean
        run: ./gradlew clean

      - name: Unit tests
        run: ./gradlew testó

      - name: Unit tests results
        uses: actions/upload-artifact@v1
        with:
          name: unit-tests-results
          path: app/build/reports/tests/testDebugUnitTest/index.html
